### PR TITLE
Fixed unhandled exception in `withZoneArena`

### LINKED ISSUE #107: `withZoneArena` is leaking a `Future`
When the computation returns a `Future` `withZoneArena` creates a new `Future` but does not return it:
https://github.com/dart-lang/ffi/blob/41459436d576c423d3844aad7970b32d02dbd0a9/lib/src/arena.dart#L153

If the original `Future` rejects, the `Future` created in `withZoneArena` causes an unhandled exception.

### PR DESCRIPTION
**Pull request by dcharkes**
Closes #107.

### CODE REVIEW

File: test/arena_test.dart [hunk 1]
```diff
@@ -163,6 +163,27 @@ void main() async {
     expect(freed.single, 1234);
   });
 
+  test('zone future error', () async {
+    bool caughtError = false;
+    bool uncaughtError = false;
+    final future = runZonedGuarded(() {
+      return withZoneArena(() async {
+        throw Exception('Exception 4');
+        // ignore: dead_code
```
Comment (lrhn) [inline test/arena_test.dart:172]: Why do you have dead code here?
If the inference gets in your way, could you just provide a type argument to `withZoneArena`? (Would it be `withZoneArena<Future<int>>`?)

**Review by lrhn — APPROVED** [review]
